services:
  app:
    image: ghcr.io/azsumtoshko/catan-helper:latest
    container_name: catan-helper
    ports:
      - "8282:8282"
    restart: unless-stopped

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    # Check for updates every 60 seconds (1 minute) and remove old images
    command: --interval 60 --cleanup
    restart: unless-stopped
